### ISSUE TITLE
endless loops

### ISSUE THREAD

**Issue by rksm** [LivelyKernel/lively.ast#5]
despite of cfb7db5c859a60c54ba6acd9d65a445548bf7136 there are still endless loops that cause freezes and browser crashes. To reproduce:
1. lively.next -> open modules browser
2. open lively.ast/lib/query.js

@levjj

**Comment by levjj** [comment]
Yeah, this is probably caused by deepCopy and cycles in the AST. The purpose of cfb7db5c859a60c54ba6acd9d65a445548bf7136 was to prevent cyclic references by copying. However, there seems to be edge cases where the AST already contains cyclic reference even before references are resolved. Therefore, the `deepCopy` which was meant to prevent a cycle caused an endless loop. Removing these calls in cfb7db5c859a60c54ba6acd9d65a445548bf7136 doesn't not fix the issue, it only pushes it back to the next `deepCopy`.

One fix would be to look at the specific cases and find examples that cause these cyclic references. Another option would be to remove _all_ calls to deepCopy in lively.ast (because this should not really be necessary IMO).

**Comment by rksm** [comment]
Well, we need to copy an AST somehow, at the two places this is being done right now it is necessary but apart from that it is a pretty basic operation. I think, since it is a _tree_ `deepCopy` shouldn't have any problems. If you really can't keep the circular refs external from the actual AST, which I would prefer, then you might be able to implement of an AST copy that deals with circ refs.

**Comment by levjj** [comment]
Yeah, a deepCopy that can handle cycles would be another option.

BTW, the reference resolution does _not_ add any circular references (at least before cfb7db5). The fact that it still crashed indicates that there were already circular references in the AST before references were resolved. Maybe these were a result of parsing?

**Comment by rksm** [comment]
That is unlikely, we haven't seen this kind of freezes before. The acorn parser is compliant with the ES tree spec and produces a real tree. The only things we manually add to the nodes are source properties and optionally ast indexes. Comments can be added using acorn as well and we make them available at the root node manually but this also don't create loops.

**Comment by levjj** [comment]
If you can find a test that crashes with the deepCopy calls that were removed in cfb7db5, then the AST already included cycles by the time references were resolved. The only purpose of these calls was to ensure that no cycles are created.

**Comment by rksm** [comment]
Test is in first message and I'm 100% sure that this worked well a week ago.

**Comment by rksm** [comment]
OK, found the issue, your commit fixed it but we need a rebuild as we do not force module reloads on bootstrap. Thanks :)

**Comment by rksm** [comment]
However, we still need to be able to reliably copy an AST.

**Comment by levjj** [comment]
Yep. I don't think that commit is a "good" fix but maybe it works until we find the root issue. (If resolveReferences is not introducing cycles then who is?)
